### PR TITLE
fix: parse CPI instructions

### LINKED ISSUE #215: Can't detect inner instruction match when using `TransactionPipeline`
# Context
I'm trying to use the `TransactionPipeline` to parse list of instructions for Meteora DLMM program, the issue is that if the outer instruction can't be decoded, all the inner instructions will be ignored. Probably the logic should be considered is here 
```rust
fn parse_instructions(&self, instructions: &[NestedInstruction]) -> Vec<ParsedInstruction<T>> {
        log::trace!(
            "TransactionPipe::parse_instructions(instructions: {:?})",
            instructions
        );

        let mut parsed_instructions: Vec<ParsedInstruction<T>> = vec![];

        instructions.iter().for_each(|nested_instr| {
            // if the outer instruction can't be decoded, inner instructions will be skipped
            if let Some(parsed) = T::parse_instruction(&nested_instr.instruction) {
                parsed_instructions.push(ParsedInstruction {
                    program_id: nested_instr.instruction.program_id,
                    instruction: parsed,
                    inner_instructions: self.parse_instructions(&nested_instr.inner_instructions),
                });
            }
        });

        parsed_instructions
    }
```

Example tx: https://solscan.io/tx/2QKrNmrpbpFgYA37kva9JvCnKMert6L33MYyqy97KGVJikmnKCDzx351Ax9bKa3sWCAceX4GRtdHJZkEpP2h92j4

### PR DESCRIPTION
**Pull request by sonicfromnewyoke**
closes #215

### CODE REVIEW

File: crates/core/src/instruction.rs [hunk 1]
```diff
@@ -247,39 +266,132 @@ impl Deref for NestedInstructions {
...
+                .push(nested_instruction);
         }
 
-        NestedInstructions(result)
+        nested_ixs
+    }
+}
+
+#[cfg(test)]
+mod tests {
```
Comment (quangkeu95) [inline crates/core/src/instruction.rs:293]: can we have real transaction example to test parsing the nested instructions too?

Comment (sonicfromnewyoke) [reply crates/core/src/instruction.rs:293]: both of txs and their inner ixes are tested in the scope of [transformers](https://github.com/sevenlabs-hq/carbon/pull/221/files/780e002bb179b981dd286f09ac1e3e2d30e8a5ef#diff-ef5c17c0eeffa2d2c9b4cb274fc571f8b31c6a3c18cfe4aaf6e4f37cf64dca85R545)

**Review by KellianDev — APPROVED** [review]
finally had time to go through this, lgtm atm
